/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface RenderRequest {
  templatePath: string
  outPath: string
  width: number
  height: number
  /** Arbitrary JSON-like object from TS (Record<string, any>) */
  data: any
  /** Optional render tuning */
  scale?: number
  animationTime?: number
  /** Optional extra fonts (paths on disk) */
  fontPaths?: Array<string>
}

export declare function renderTemplateToPng(req: RenderRequest): Promise<void>
